#!/bin/bash

# ----------------------------------------------------------------------
# MakeAllChains.sh
#
# Generate pairwise chain-file commands from a Progressive Cactus HAL file.
#
# This script does two things:
#   1. For each species, extract genome sequence from the HAL file and
#      create the .2bit and .bed files needed for chain generation.
#   2. For each ordered species pair, write commands to:
#        - run halLiftover
#        - convert PSL coordinates to positive target strand using pslPosTarget
#        - convert PSL alignments to chain files using axtChain
#
# This script creates two command files:
#   commands.txt   = halLiftover + pslPosTarget commands
#   commands2.txt  = axtChain commands
#
# Run them after this script finishes:
#   bash commands.txt
#   bash commands2.txt
# ----------------------------------------------------------------------

# Stop if any command fails
set -e

# -----------------------
# Paths
# -----------------------

# Project directory
BASE_DIR=$(pwd)

# HAL tools directory
# This should contain: hal2fasta, halStats, halLiftover
HDIR=thirdparty/hal/bin

# UCSC tools directory
# This should contain: faToTwoBit, pslPosTarget, axtChain
UCSC_DIR=thirdparty/ucsc_tools

# HAL file generated by Progressive Cactus
HAL=results/cactus_alignment/kidneySpecies_rn7.hal

# Output directories
PSL_DIR=results/chain_files_res/results_halLiftover
CHAIN_DIR=results/chain_files_res/chain_files
WORK_DIR=results/chain_files_res/species_files

mkdir -p ${PSL_DIR}
mkdir -p ${CHAIN_DIR}
mkdir -p ${WORK_DIR}

# Remove old command files if present
if [ -e commands.txt ]; then
    rm commands.txt
fi

if [ -e commands2.txt ]; then
    rm commands2.txt
fi

# -----------------------
# Species list
# -----------------------
# These names must exactly match the species names inside the HAL file.

SPECIES_LIST="acomys_dimidiatus acomys_russatus homo_sapiens mus_musculus sus_scrofa rattus_norvegicus macaca_fas"

# -----------------------
# Step 1: Make .2bit and .bed files
# -----------------------
# hal2fasta extracts each species genome from the HAL file.
# faToTwoBit converts the FASTA stream to .2bit format.
# halStats --bedSequences writes the sequence intervals for each species.

for S1 in ${SPECIES_LIST}
do
    echo "Preparing files for ${S1}"

    ${HDIR}/hal2fasta ${HAL} ${S1} \
        | ${UCSC_DIR}/faToTwoBit stdin ${WORK_DIR}/${S1}.2bit

    ${HDIR}/halStats --bedSequences ${S1} ${HAL} \
        > ${WORK_DIR}/${S1}.bed
done

# -----------------------
# Step 2: Write pairwise commands
# -----------------------
# For every species pair S1 -> S2:
#   1. halLiftover maps all intervals from S1 to S2 and outputs PSL.
#   2. pslPosTarget forces target coordinates to the positive strand.
#   3. axtChain converts PSL to chain format.
#
# Note:
# The chain file is named ${S2}_to_${S1}.linearGap_medium.chain
# to match the convention used in the original project script.

for S1 in ${SPECIES_LIST}
do
    for S2 in ${SPECIES_LIST}
    do
        if [ ${S1} == ${S2} ]; then
            continue
        fi

        echo -e "Writing commands for ${S1}\t${S2}"

        PSL=${PSL_DIR}/${S1}_to_${S2}.psl
        CHAIN=${CHAIN_DIR}/${S2}_to_${S1}.linearGap_medium.chain

        echo "${HDIR}/halLiftover --hdf5InMemory --outPSL ${HAL} ${S1} ${WORK_DIR}/${S1}.bed ${S2} /dev/stdout | ${UCSC_DIR}/pslPosTarget stdin ${PSL}" \
            >> commands.txt

        echo "${UCSC_DIR}/axtChain -psl -linearGap=medium ${PSL} ${WORK_DIR}/${S2}.2bit ${WORK_DIR}/${S1}.2bit ${CHAIN}" \
            >> commands2.txt
    done
done

echo "Next run:"
echo "  bash commands.txt"
echo "  bash commands2.txt"
